### ISSUE TITLE
Observed property type

### ISSUE THREAD

**Issue by dr-shorthair** [ilkkarinne/omsf-profile#2]
The element omsf:observedProperty is declared thus: 

<xsd:element name="observedProperty" type="omsf:PropertyNameCodeType" minOccurs="1" />

leading to the example: 

<omsf:observedProperty codeSpace="cf-standard-names/46">air_temperature</omsf:observedProperty>

In GML the @codeSpace attribute should carry a URI. 
I don't see the need for a new property type here. You can just use gml:ReferenceType 
<xsd:element name="observedProperty" type="gml:ReferenceType" minOccurs="1" />

then catprure the same data using the xlink attributes thus: 

<omsf:observedProperty xlink:href="http://vocab.nerc.ac.uk/collection/P07/current/CFSN0023/" xlink:title="air_temperature" />

**Comment by ilkkarinne** [comment]
@dr-shorthair: the gml:ReferenceType is what I had in the first version. However, after quickly checking with QGIS, it seems that gml:ReferenceType elements are not displayed at all in the feature info tool, while the ones extending the gml:CodeType are showing the code value.

It's clear that the design choices of just one application should not carry too much weight in this matter, but I thought the maybe the reference-only type elements are more difficult to access in other current applications/libraries too. 

Also the GML Simple Features Profile suggests using the gml:CodeType for code lists, and not gml:ReferenceType. I guess the using the reference is a more common approach these days (just a single URI without the complications of codeSpaces)

**Comment by ilkkarinne** [comment]
Changing the observedProperty to a gml:ReferenceType, as others also have sent me the same feedback
