### ISSUE TITLE
Combine time and value result elements in TimeseriesObservation

### ISSUE THREAD

**Issue by sgrellet** [ilkkarinne/omsf-profile#3]
The latest version using SF-1 splits time and value pair from each other. Meaning a client would have to count time and value to know who is associated to whom.

We discussed the possibility to stay within SF-0 and add an extra omsf:resultTokenSeparator attribute that could then allow in the <omsf:resultValues> to have something like
<omsf:resultTokenSeparator>|</omsf:resultTokenSeparator>
<omsf:resultValues>12.5|2017-08-17T12:00:00Z 12.0|2017-08-17T13:00:00Z 11.0|2017-08-17T14:00:00Z 13.2|2017-08-17T15:00:00Z  13.5|2017-08-17T16:00:00Z  14.1|2017-08-17T17:00:00Z </omsf:resultValues>

Another way, if you go for SF-1: why not considering a user-defined property types to recouple time and value ?

**Comment by ilkkarinne** [comment]
Hi @sgrellet: I would not like to make the time-value pair encoded within the resultValues property: I think that would require custom parsing & encoding code to produce and access values. I do agree, that splitting the time series time and value pair in two attributes is not ideal either.

SF-1 indeed allows for user-defined property types, so we could have something like
```xml
<xsd:complexType name="TimeValuePairType">
   <xsd:sequence>
      <xsd:element name="time" type="xsd:dateTime" minOccurs="1" />
      <xsd:element name="value" type="xsd:double" minOccurs="1" />
   </xsd:sequence>
</xsd:complexType>
```

and

``xml
<xsd:complexType name="TimeseriesObservationType">
   <xsd:complexContent>
      <xsd:extension base="omsf:AbstractObservationType">
        <xsd:sequence>
          <xsd:element name="resultUnitOfMeasure" type="gml:CodeType" minOccurs="1"/>
          <xsd:element name="resultValue" type="omsf:TimeValuePairType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
      </xsd:extension>
    </xsd:complexContent>
</xsd:complexType>
```

This is getting closer to the complexity of the TimeValuePairType of TimeseriesML, but I guess it would still be manageable. The question I have with using the user-defined properties is how well are those supported in current (simple) feature handling software libraries (GeoTools etc)?

**Comment by sgrellet** [comment]
The recent GDAL GMLAS driver (http://www.gdal.org/drv_gmlas.html) will handle that smoothly as it is schema driven. 
For the others, better testing on a sample file.
